# Generated by Django 5.0.1 on 2024-02-22 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('default_accounting_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryLines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accounting_date', models.DateField()),
                ('account', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('reconciled', models.BooleanField()),
                ('currency', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('account_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=20)),
            ],
        ),
    ]
