# Generated by Django 3.2.24 on 2024-02-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "Account"},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Currency", "verbose_name_plural": "Currency"},
        ),
        migrations.AlterModelOptions(
            name="journalentrylines",
            options={
                "verbose_name": "JournalEntryLine",
                "verbose_name_plural": "JournalEntryLines",
            },
        ),
    ]
